engines:
  eslint:
    enabled: true
    checks:
      import/no-unresolved:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- server/test/
- template/
- node_modules/
- client/
checks:
  file-lines:
    enabled: false
  complex-logic:
    enabled: false
  method-complexity:
      enabled: false
  method-lines:
      enabled: false
  nested-control-flow:
      enabled: false

