env:
  global:
    - CC_TEST_REPORTER_ID=74167dae5f0cc537153563074da597f0fa65ed4efdd2b9137b1ee3994ea0d4cf
sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - psql -c 'drop database if exists libdb;' -U postgres
  - psql -c 'create database libdb;' -U postgres
  - npm install jest
  - npm install -g codeclimate-test-reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run client:test
after_success: 
  - 'npm run coveralls'
  - codeclimate-test-reporter < coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  postgresql: "9.3"
