sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'drop database if exists libdb;' -U postgres
  - psql -c 'create database libdb;' -U postgres
script:
  - npm test
after_script:
  - 'npm run coveralls'

after_success: 'npm run coveralls'

addons:
  postgresql: "9.3"
