sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - psql -c 'drop database if exists libdb;' -U postgres
  - psql -c 'create database libdb;' -U postgres
  - npm install jest
script:
  - npm run nyc
after_success: 
  - 'npm run coveralls'

addons:
  postgresql: "9.3"
