const books = [
  {
    id: 1,
    bookId: 1,
    bookTitle: 'THE PEOPLE IN THE TREE',
    author: 'Y. Hayan',
    category: 'Adventure',
    isbn: '345798465',
    stocknumber: '2',
    image: 'l1.jpg',
    summary: 'Lorem Ipronic typesetting, remaininised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
  },
  {
    id: 2,
    bookId: 2,
    bookTitle: 'THE LATE PARADE',
    author: 'F. Adam',
    category: 'Adventure',
    isbn: '234560878',
    stocknumber: '0',
    image: 'l2.jpg',
    summary: 'It is a long established fact thaorem Ipsu uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)',
  },
  {
    id: 3,
    bookId: 3,
    bookTitle: 'I AM THE WOLF',
    author: 'L. Mark',
    category: 'Music',
    isbn: '4678980976',
    stocknumber: '5',
    image: 'l3.jpg',
    summary: 'There are many variations of passages of Lorem Ipsum available, but the majority orem Ipsum generators on the Internet tend to repeat predefined chunks as necessary',

  },
  {
    id: 4,
    bookId: 4,
    bookTitle: 'THE PALE NORTH',
    author: 'H. Clayton',
    category: 'Adventure',
    isbn: '34567887655',
    stocknumber: '3',
    image: 'l4.jpg',
    summary: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from ',
  },
  {
    id: 5,
    bookId: 5,
    bookTitle: 'ADULTOLESENCE',
    author: 'G. Hannah',
    category: 'Romance',
    isbn: '45678974567',
    stocknumber: '10',
    image: 'l5.jpg',
    summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urum.'
  },
  {
    id: 6,
    bookId: 6,
    bookTitle: 'WHAT IT MEANS WHEN A MAN FALL FROM SKY',
    author: 'L. Nneka',
    category: 'Adventure',
    isbn: '567244567',
    stocknumber: '10',
    image: 'l6.jpg',
    summary: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium?'
  },
  {
    id: 7,
    bookId: 7,
    bookTitle: 'THE SONG AND THE SILENCE',
    author: 'Y. Johnson',
    category: 'Music',
    isbn: '64578974567',
    stocknumber: '10',
    image: 'l7.jpg',
    summary: 'But I must explain to you how all this mists no resultant pleasure  ducimus qui blanditiis praesentium voluptatum culpa qui officia ?'
  },
  {
    id: 8,
    bookId: 8,
    bookTitle: 'THE ILIAD HOMMER',
    author: 'P. Green',
    category: 'Action',
    isbn: '787890974567',
    stocknumber: '8',
    image: 'l8.jpg',
    summary: 'At vero eos et accusamus et iuse delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.'
  },
];

export default books;
