module.exports = {
  up: queryInterface =>
    queryInterface.bulkInsert('Books', [
      {
        bookTitle: 'THE PEOPLE IN THE TREE',
        author: 'Y. Hayan',
        category: 'Adventure',
        isbn: '345798465',
        stocknumber: '2',
        image: 'l1.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookTitle: 'THE LATE PARADE',
        author: 'F. Adam',
        category: 'Adventure',
        isbn: '234560878',
        stocknumber: '0',
        image: 'l2.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookTitle: 'I AM THE WOLF',
        author: 'L. Mark',
        category: 'Music',
        isbn: '4678980976',
        stocknumber: '5',
        image: 'l3.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookTitle: 'THE PALE NORTH',
        author: 'H. Clayton',
        category: 'Adventure',
        isbn: '34567887655',
        stocknumber: '3',
        image: 'l4.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookTitle: 'ADULTOLESENCE',
        author: 'G. Hannah',
        category: 'Romance',
        isbn: '45678974567',
        stocknumber: '10',
        image: 'l5.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookTitle: 'WHAT IT MEANS WHEN A MAN FALL FROM SKY',
        author: 'L. Nneka',
        category: 'Adventure',
        isbn: '567244567',
        stocknumber: '10',
        image: 'l6.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookTitle: 'THE SONG AND THE SILENCE',
        author: 'Y. Johnson',
        category: 'Music',
        isbn: '64578974567',
        stocknumber: '10',
        image: 'l7.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookTitle: 'THE ILIAD HOMMER',
        author: 'P. Green',
        category: 'Action',
        isbn: '787890974567',
        stocknumber: '8',
        image: 'l8.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

    ], {}),
  down: queryInterface =>
    queryInterface.bulkDelete('Books', null, {}),
};
